version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=accounts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

#  main-service:
#    build:
#      context: .
#      dockerfile: ./mainservice/Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db/accounts
#      - SPRING_DATASOURCE_USERNAME=mainservice
#      - SPRING_DATASOURCE_PASSWORD=HfG3@fj0OfjvHdkf234ja
#      - SPRING_DATASOURCE_PORT=5432
#volumes:
#  postgres-data:
#    driver: local