version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: SSL://localhost:9092
      KAFKA_LISTENERS: SSL://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: keystore_password
      KAFKA_SSL_KEY_PASSWORD: key_password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: truststore_password
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.2,TLSv1.1,TLSv1
      KAFKA_SSL_PROTOCOL: TLS
      KAFKA_SECURITY_PROTOCOL: SSL
    volumes:
      - /d/practice_2/sigmaton/keystore.jks:/etc/kafka/secrets/keystore.jks
      - /d/practice_2/sigmaton/truststore.jks:/etc/kafka/secrets/truststore.jks

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=accounts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  main-service:
#    build:
#      context: .
#      dockerfile: ./mainservice/Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db/accounts
#      - SPRING_DATASOURCE_USERNAME=mainservice
#      - SPRING_DATASOURCE_PASSWORD=HfG3@fj0OfjvHdkf234ja
#      - SPRING_DATASOURCE_PORT=5432
volumes:
  postgres-data:
    driver: local