spring:
  application:
    name: main-service
    kafka:
      bootstrap-servers: localhost:9092
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/accounts
  jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
  flyway:
    enabled: false
server:
  port: 8081