spring:
  application:
    name: main-service
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: transactions_group
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/accounts
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

server:
  port: 8081
