spring:
  application:
    name: main-service
    kafka:
      bootstrap-servers: localhost:9092
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/accounts
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
server:
  port: 8081