spring:
  application:
    name: main-service
    kafka:
      key-store-location: /keystore.jks
      ssl.key-store-password: keystore_password
      ssl.key-password: key_password
      ssl.trust-store-location: /truststore.jks
      ssl.trust-store-password: truststore_password
      consumer:
        bootstrap-servers: localhost:9092
        group-id: transactions_group
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/accounts
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

server:
  port: 8081
